import pandas as pd

def get_space_data():
    # Pull in the data into a pandas data frame
    df = pd.read_csv('../data/Space_Corrected.csv')
    
    # drop excess columns generated by pandas
    df.drop(columns=['Unnamed: 0', 'Unnamed: 0.1'], inplace = True)
    
    # Change the date column to a pandas datetime type
    df.Datum = pd.to_datetime(df.Datum)
    
    # Set the index to be the datetime column, then drop it from the dataframe
    df.set_index(df.Datum, inplace=True)
    return df